@startuml
left to right direction
skinparam packageStyle rectangle

actor "Hội viên" as Member
actor "Nhân viên quản lý" as Staff
actor "Huấn luyện viên\n(PT)" as PT
actor "Chủ phòng tập" as Owner
actor "Hệ thống thanh toán\n(Ngân hàng số, ví điện tử,...)" as PaymentSystem

rectangle "Hệ thống quản lý phòng tập Gym" {

  rectangle "Quản lý đăng nhập & phân quyền" {
    usecase "UC00\nĐăng nhập" as UC00
    usecase "UC01\nĐăng xuất" as UC01
    usecase "UC02\nQuên mật khẩu" as UC02
    usecase "Phân quyền người dùng" as Role
  }

  rectangle "Quản lý hội viên & thanh toán" {
    usecase "UC03\nĐăng ký hội viên mới" as UC03
    usecase "UC04\nGia hạn gói tập" as UC04
    usecase "Thanh toán" as Payment
    usecase "Quản lý giao dịch tài chính" as Transaction
  }

  rectangle "Quản lý lịch tập & đánh giá" {
    usecase "UC05\nTheo dõi lịch tập và\nTự động ghi nhận" as UC05
    usecase "UC06\nTheo dõi và Đánh giá tiến độ" as UC06
    usecase "UC07\nGửi phản hồi" as UC07
  }

  rectangle "Quản lý phòng tập & thiết bị" {
    usecase "UC08\nQuản lý thông tin phòng tập" as UC08
    usecase "UC09\nQuản lý và Bảo trì thiết bị" as UC09
  }

  rectangle "Quản trị hệ thống & báo cáo" {
    usecase "UC10\nThiết lập gói tập" as UC10
    usecase "UC11\nQuản lý nhân sự" as UC11
    usecase "UC12\nXem báo cáo thống kê" as UC12
  }
}

Member --> UC00
Member --> UC01
Member --> UC02
Member --> UC04
Member --> UC05
Member --> UC06
Member --> UC07
Member --> Payment

Staff --> UC00
Staff --> UC01
Staff --> UC02
Staff --> UC03
Staff --> UC04
Staff --> UC08
Staff --> UC09
Staff --> UC10
Staff --> Transaction

PT --> UC00
PT --> UC01
PT --> UC02
PT --> UC05
PT --> UC06
PT --> UC07

Owner --> UC00
Owner --> Role
Owner --> UC10
Owner --> UC11
Owner --> UC12
Owner --> Transaction

Payment --> PaymentSystem
Transaction ..> Payment : <<include>>
UC03 ..> Payment : <<include>>
UC04 ..> Payment : <<include>>
@enduml